services:
  lantern:
    container_name: lantern
    image: lantern:7.0.0-beta2
    build: .
    ports:
      # UI
      - target: 80
        host_ip: 127.0.0.1
        published: 39331
        protocol: tcp
      # HTTP(S) proxy
      - target: 8080
        host_ip: 127.0.0.1
        published: 39332
        protocol: tcp
      # SOCKS proxy
      - target: 1080
        host_ip: 127.0.0.1
        published: 39333
        protocol: tcp
    volumes:
      - data:/home/lantern/.lantern
volumes:
  data:
    name: lantern
