services:
  lantern:
    container_name: lantern
    image: docker.io/magras/lantern:7.0.0-beta2
    build: .
    ports:
      # UI
      - target: 80
        host_ip: 127.0.0.1
        published: ${UI_PORT:-39331}
        protocol: tcp
      # HTTP(S) proxy
      - target: 8080
        host_ip: 127.0.0.1
        published: ${HTTP_PORT:-39332}
        protocol: tcp
      # SOCKS proxy
      - target: 1080
        host_ip: 127.0.0.1
        published: ${SOCKS_PORT:-39333}
        protocol: tcp
    volumes:
      - data:/home/lantern/.lantern
volumes:
  data:
    name: lantern
