name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "Dockerfile"
      - "settings.yaml"
      - "binaries"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - run: >-
        echo "LANTERN_VERSION=$(
          dpkg-deb -I binaries/lantern-installer-64-bit.deb |
          sed -n 's/^ Version: \(.*\)/\1/p'
        )" >> $GITHUB_ENV

    - uses: docker/setup-buildx-action@v3

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: magras/lantern
        tags: |
          type=semver,pattern={{version}},value=${{env.LANTERN_VERSION}}

    - uses: docker/build-push-action@v6
      with:
        context: .
        tags: magras/lantern:${{env.LANTERN_VERSION}}
        labels: ${{steps.meta.outputs.labels}}
        cache-to: type=gha
        cache-from: type=gha

    - uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: magras/lantern:${{env.LANTERN_VERSION}}
        format: sarif
        output: trivy.sarif

    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy.sarif

    - uses: docker/login-action@v3
      with:
        username: magras
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{github.ref_type == 'branch' && github.ref_name == 'main'}}
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        cache-to: type=gha
        cache-from: type=gha
