name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "Dockerfile"
      - "settings.yaml"
      - "binaries"
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: true

    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: docker.io/magras/lantern
        tags: |
          type=semver,pattern={{version}}
          type=edge
          type=ref,event=pr

    - uses: docker/login-action@v2
      with:
        username: magras
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{github.event_name == 'push'}}
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        cache-to: type=inline
        cache-from: type=registry,ref=magras/lantern:edge
