name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "Dockerfile"
      - "settings.yaml"
      - "binaries"
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: true

    - run: >-
        echo "LANTERN_VERSION=$(
          dpkg-deb -I binaries/lantern-installer-64-bit.deb |
          sed -n 's/^ Version: \(.*\)/\1/p'
        )" >> $GITHUB_ENV

    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: magras/lantern
        tags: |
          type=edge,priority=3
          type=ref,event=pr,priority=2
          type=semver,pattern={{version}},value=${{env.LANTERN_VERSION}},priority=1

    - uses: docker/login-action@v2
      with:
        username: magras
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{github.event_name != 'pull_request'}}
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        cache-to: type=inline
        cache-from: type=registry,ref=magras/lantern:edge
